services:
  spring:
    container_name: spring-server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    volumes:
      - ./src:/app/src
  postgresql:
    container_name: postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgre-data:/var/lib/postgresql/data
volumes:
  postgre-data: