spring:
  devtools:
    restart:
      enabled: true
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    database: postgresql
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              spi: trace
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: docker-dev
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  
